# Generated by Django 3.2 on 2021-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_podcast', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=100)),
                ('duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_song', models.CharField(max_length=100)),
                ('duration_in_number_of_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
        ),
    ]
