# Generated by Django 3.2 on 2021-04-19 09:18

import audioFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='audiofiletype',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='podcast',
            name='audiofiletype',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='audiofiletype',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateTimeField(validators=[audioFiles.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(validators=[audioFiles.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(validators=[audioFiles.models.validate_date]),
        ),
    ]
