# Generated by Django 3.2 on 2021-04-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0003_auto_20210419_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='audiofiletype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audiofiletype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='audiofiletype',
            field=models.CharField(max_length=10),
        ),
    ]
