# Generated by Django 3.2 on 2021-04-20 06:19

import audioFiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioFiles', '0004_auto_20210419_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFiles.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFiles.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, validators=[audioFiles.models.validate_date]),
        ),
    ]
